### ISSUE TITLE
Is the "type" function overriden?

### ISSUE THREAD

**Issue by siamak-haschemi** [codeboardio/codeboard#11]
Hi, using a Python3 codeboard,

```
print("type: ", type(5))
print("type: ", type(5.5))
print("type: ", type("test"))    
```

gives me:

```
type:  
type:  
type:  
```

instead of:

```
type:  <class 'int'>
type:  <class 'float'>
type:  <class 'str'>
```

Can I do something about this?

**Comment by codeboardio** [comment]
Hi,

If you're the Owner of the project l, in the IDE you can switch the View
setting to Text output. When doing that, you should see the correct output.

Let me know if that works.


Siamak Haschemi ***@***.***> schrieb am Fr., 14. Apr. 2023,
10:25:

**Comment by siamak-haschemi** [comment]
@codeboardio That works! Thank you. So `<class 'int'>` was interpreted as HTML and not shown, I understand!
