### ISSUE TITLE
Codeboard website giving error 500 on compilation

### ISSUE THREAD

**Issue by harsh3195** [codeboardio/codeboard#8]
Have been seeing this error on the website for the past hour. I use codeboard for my live classes on programming. Is this something that was a scheduled maintenance job or an unexpected error? It would be great if anyone could tell me how to receive updates about such issues in the future.

<img width="774" alt="Screen Shot 2020-09-05 at 10 56 48 PM" src="https://user-images.githubusercontent.com/16266183/92310360-308a7000-efcb-11ea-84c2-47158b18b561.png">

**Comment by haches** [comment]
Hi @harsh3195!

Thanks for reporting. The issue should be fixed now. Scheduled maintenance downtimes get announced on the website. In this case, it was a server crash that required manual intervention to fix. Sorry about the inconvenience.

**Comment by harsh3195** [comment]
The issue is fixed.  Thanks for the swift response. 👍
